"""
Django settings for day06 project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kbk=_g@)h4zdwttrbx+oyi$8=y9*byr2(_ska!to(%_4(m)&_p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    # 'django.contrib.auth',
    # 'django.contrib.contenttypes',
    # 'django.contrib.sessions',
    # 'django.contrib.messages',
    'django.contrib.staticfiles',
    'web.apps.WebConfig',
]

MIDDLEWARE = [
    # 'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'utils.middleware.AuthMiddleware'
]

ROOT_URLCONF = 'day06.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                # 'django.contrib.auth.context_processors.auth',
                # 'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'day06.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'day06',  # 数据库名字
        'USER': 'root',
        'PASSWORD': '123',
        'HOST': '127.0.0.1',  # ip
        'PORT': 3306,
    }
}



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#cache配置
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 100},
            "PASSWORD": "redis123",
        }
    }
}

# session
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'



# =========================================================
# 自定义业务配置 (变量名必须大写，加上 NB_ 前缀防冲突)
# =========================================================

# 1. 登录成功后的默认跳转主页
LOGIN_HOME = "/level/list/"

# 2. 之前我们在登录视图存入 Session 的键名 (保持一致)
NB_SESSION_KEY = "user_info"

# 3. 登录页面的 URL (用来给未登录的人踢回去)
NB_LOGIN_URL = "/login/"

# 4. 白名单 URL (不需要登录就能访问的页面，比如登录页、发短信的接口)
NB_WHITE_URL = ['/login/', '/sms/login/', '/sms/send/']

# 5. 权限字典：不同角色能访问的 URL 的 name 集合
# 这里的 "level_list", "level_add" 等必须和你 urls.py 里面的 name="xxx" 对应！
NB_PERMISSION = {
    "ADMIN": {
        "level_list": "级别列表",
        "level_add": "级别添加",
        "level_edit": "级别编辑",
        "level_delete": "级别删除",
        "customer_list":"用户列表",
        "customer_add":"用户添加",
        "customer_edit":"用户编辑",
        "customer_delete":"用户删除",
        "customer_charge":"用户交易信息",
        "customer_charge_add":"用户交易信息添加",
        "policy_list":"价格策略列表",
        "policy_add":"价格策略添加",
        "policy_delete":"价格策略删除",
        "policy_edit":"价格策略编辑",


    },
    "CUSTOMER": {
        "level_list": "级别列表",
        "my_order_list":"我的订单",
        "my_order_add":"下单",
        "my_order_cancel":"撤单",

    }
}

# 6. 动态菜单字典：不同角色登录后，左侧显示的菜单结构
NB_MENU = {
    "ADMIN": [
        # 给级别管理配一个皇冠图标
        {"text": "级别管理", "url": "/level/list/", "icon": "fas fa-crown"},
        # 给用户管理配一个人群图标
        {"text": "用户管理", "url": "/customer/list/", "icon": "fas fa-users"},
        # 给订单管理配一个清单图标
        {"text": "价格策略", "url": "/policy/list/", "icon": "fas fa-clipboard-list"},
    ],
    "CUSTOMER": [
        {"text": "我的订单", "url": "/my/order/list/", "icon": "fas fa-shopping-cart"},
        {"text": "账户流水", "url": "/xxx/xx/", "icon": "fas fa-wallet"},
    ]
}


